"""Writes docs/MODULES.md: every file in src/, grouped, with the first line of its docstring.

    python scripts/modules_doc.py

Generated, so it cannot drift from the code. A module that is in no group lands under "Other",
which is the prompt to place it.
"""

import ast
import os

ROOT = os.path.join(os.path.dirname(__file__), "..")
SRC = os.path.join(ROOT, "src")

GROUPS = (
	("Runs the accounts", ("main", "daily_loop", "search_scheduler", "search_only", "rewards_tasks", "browser", "tab_utils", "quests", "element_selectors", "desktop_utils", "signin")),
	("What it searches for", ("queries", "query_sources", "query_history", "openrouter_queries", "llm_utils", "search_behavior", "trawl_client")),
	("Behaves like a person", ("behavior", "mimic_typing", "mouse_trajectory", "pacing", "schedule_plan", "features", "footprint")),
	("Keeps itself safe and visible", ("safety", "notify", "health", "journal", "run_lock", "points_log", "status", "backup", "clock", "accounts", "constants", "log_utils")),
	("One VPN per account", ("vpn_config", "isolation")),
	("Recording a person's hands", ("calibrate", "calibration", "make_behavior_profile", "typing_test", "fitts_law", "recordpress", "analyze_keypresses")),
	("Diagnostics and one-off tools", ("check_selectors", "fingerprint_probe", "inspect_rewards", "vpn_browser_check", "visualize_trajectory", "visualize_bezier_distortions", "random_image_for_visual_search")),
)


def first_line(path: str) -> str:
	try:
		with open(path, encoding="utf-8") as handle:
			text = ast.get_docstring(ast.parse(handle.read())) or ""
	except (OSError, SyntaxError):
		return "(unreadable)"

	line = text.strip().splitlines()[0] if text.strip() else "(no description)"

	return line.rstrip(".")


def main() -> None:
	names = sorted(f[:-3] for f in os.listdir(SRC) if f.endswith(".py"))
	placed = {name for _, members in GROUPS for name in members}
	other = [n for n in names if n not in placed]
	lines = ["# Modules", "", "Generated by `python scripts/modules_doc.py`; do not edit by hand.", ""]

	for title, members in GROUPS + (("Other (place these in a group)", tuple(other)),):
		present = [m for m in members if m in names]

		if not present:
			continue

		lines += [f"## {title}", ""]
		lines += [f"- `src/{name}.py`: {first_line(os.path.join(SRC, name + '.py'))}" for name in present]
		lines.append("")

	with open(os.path.join(ROOT, "docs", "MODULES.md"), "w", encoding="utf-8", newline="\n") as handle:
		handle.write("\n".join(lines))


if __name__ == "__main__":
	main()
